<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Common/Common.csproj" />
    <ProjectReference Include="..\TranslationBatcher\TranslationBatcher.csproj" />
    <ProjectReference Include="..\RagContextRetriever\RagContextRetriever.csproj" />
    <ProjectReference Include="..\ContentChecker\ContentChecker.csproj" />
    <ProjectReference Include="..\PercentNormalizer\PercentNormalizer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
